name: Build, Test and Analyze PR

on: pull_request

jobs:
  assemble:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set Up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: "Change wrapper permissions"
        run: chmod +x ./gradlew

      - name: "Run assemble"
        run: ./gradlew assemble

  static_analysis:
    name: "Static Analysis"
    needs:
      - assemble
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set Up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: "Change wrapper permissions"
        run: chmod +x ./gradlew

      - name: "Run Ktlint Format"
        run: ./gradlew ktlintFormat

      - name: "Run Detekt"
        run: ./gradlew detektDebug

  unit_tests:
    permissions: write-all
    name: "Unit tests & Kover & Sonar"
    needs:
      - assemble
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set Up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: "Change wrapper permissions"
        run: chmod +x ./gradlew

      - name: "Run unit tests"
        run: ./gradlew testDebugUnitTest

      - name: "Generate Kover report"
        run: ./gradlew koverXmlReportDebug

      - name: "Add coverage report to PR"
        uses: mi-kas/kover-report@v1
        with:
          path: |
            ${{ github.workspace }}/app/build/reports/kover/reportDebug.xml
          title: Code Coverage
          update-comment: true
          coverage-counter-type: LINE

      - name: "Sonar"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --info
