name: Build, Test and Analyze PR

on: pull_request

jobs:
  assemble:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set Up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: "Change wrapper permissions"
        run: chmod +x ./gradlew
      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2

      - name: "Run assemble"
        run: ./gradlew assemble

  static_analysis:
    name: "Static Analysis"
    needs:
      - assemble
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set Up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: "Change wrapper permissions"
        run: chmod +x ./gradlew
      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2

      - name: "Run Ktlint Format"
        run: ./gradlew ktlintFormat

      - name: "Run Detekt"
        run: ./gradlew detektDebug

  unit_tests:
    name: "Run Unit tests"
    needs:
      - assemble
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set Up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: "Change wrapper permissions"
        run: chmod +x ./gradlew
      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2

      - name: "Run testDebugUnitTest"
        run: ./gradlew testDebugUnitTest

  sonar:
    name: "Sonar Analysis"
    needs:
      - static_analysis
      - unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set Up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: "Change wrapper permissions"
        run: chmod +x ./gradlew

      - name: "Run sonar"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --info